### ISSUE TITLE
Show cards pop up is broken (when you have more then 1 card in tableau pile)

### ISSUE THREAD

**Issue by frankk74** [jsparkes/innovation#12]
... example below was trigger by clicking on blue "3 - Alchemy" 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Control array element 1 doesn't exist.
   at Microsoft.VisualBasic.ErrObject.Raise(Int32 Number, Object Source, Object Description, Object HelpFile, Object HelpContext)
   at Microsoft.VisualBasic.Compatibility.VB6.VB6Errors.RaiseError(Int32 nError, String strMessage)
   at Microsoft.VisualBasic.Compatibility.VB6.BaseControlArray.BaseGetItem(Int16 Index)
   at Microsoft.VisualBasic.Compatibility.VB6.LabelArray.get_Item(Int16 Index)
   at Innovation.showArray.load_pictures(Int16 player, Int16 Index, String kind) in C:\Users\frankk\Projects\innovation\innovation\showArray.vb:line 67
   at Innovation.Main_Renamed.lblOppDetail_Click(Object eventSender, EventArgs eventArgs) in C:\Users\frankk\Projects\innovation\innovation\main.vb:line 8098
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies ---DELETED

![image](https://user-images.githubusercontent.com/16901967/176094756-6cf14789-befd-4c9d-a2e4-aed87c457103.png)

**Comment by jsparkes** [comment]
It seems that the compatibility LabelArray does not act exactly the same as the original.  I'm going to try replacing it with an ArrayList or regular array.

**Comment by frankk74** [comment]
I don't know these articles help or not?

https://www.developer.com/guides/the-book-of-vb-net-migrating-to-visual-basic-net-part-2/

This one about control arrays?

https://www.thoughtco.com/vbnet-what-happened-to-control-arrays-4079042

**Comment by frankk74** [comment]
The window/form works/pops up when there are no cards/images to show...

**Comment by frankk74** [comment]
This is some weird side effect of VB compatibility stuff/junk doing anything on a second form results in the above messages.

Disabled controls on showarray form but can't add cancel button because the same bug comes up. So if you want to see the piles you a form a that can't go away... addressed not fixed in [58d5be5](https://github.com/jsparkes/innovation/commit/58d5be5267e8bec9b3c50fb246653a4763b7e49a)

**Comment by frankk74** [comment]
Leaving weird window is not a good fix reopening … because about box is working I’m going to try to delete showarray form and re adding it back manually because this might just be some silly conversion code getting in the way…

**Comment by jsparkes** [comment]
I have fixed this.  We need to explicitly add the controls to the form in VB.net.

**Comment by jsparkes** [comment]
[Pull request](https://github.com/jsparkes/innovation/pull/24)

**Comment by jsparkes** [comment]
I should add that initialize_Images() is now always called, but only runs once.

**Comment by frankk74** [comment]
This got fixed by your commit f74c9b04e33671647808b4674d98028153035b1e
