### ISSUE TITLE
BUG - when testing.txt file exists causes app crash

### ISSUE THREAD

**Issue by frankk74** [jsparkes/innovation#20]
Not sure why. No vbstuff it is happening in the array functions putting arr definition at top seemed to fix push3 but seems to be failing in Unshift3 now.

Tested original code and it works fine and shipped with a commented out testing.txt file.

```System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Innovation.Main_Renamed.launch_game(Object& players) in C:\Users\frankk\Projects\innovation\innovation\main.vb:line 797
   at Innovation.Main_Renamed.cmd2Players_Click(Object eventSender, EventArgs eventArgs) in C:\Users\frankk\Projects\innovation\innovation\main.vb:line 684
   at System.Windows.Forms.Control.OnClick(EventArgs e)

**Comment by frankk74** [comment]
not reproducible
